clc;
clear all;
pred_index=[50,75,100,125];
c1_pf=[125,81,58,28];
c1_real=[122,97,72,47];
pred_index_c2=[50,75,100];
c2_pf=[66,18,4];
c2_real=[55,30,5];
c3_pf=[118,72,50,30];
c3_real=[110,85,60,35];
figure;
hold on;
plot(pred_index,c1_pf,'-ro','LineWidth',2);
plot(pred_index,c1_real,'-bs','LineWidth',2);
title('Robustness for Cell 1');
xlabel('prediction start point cycle');
ylabel('RUL cycles');
legend('Using PF','From data');
figure;
hold on;
plot(pred_index_c2,c2_pf,'-ro','LineWidth',2);
plot(pred_index_c2,c2_real,'-bs','LineWidth',2);
title('Robustness for Cell 2');
xlabel('prediction start point cycle');
ylabel('RUL cycles');
legend('Using PF','From data');
figure;
hold on;
plot(pred_index,c3_pf,'-ro','LineWidth',2);
plot(pred_index,c3_real,'-bs','LineWidth',2);
title('Robustness for Cell 3');
xlabel('prediction start point cycle');
ylabel('RUL cycles');
legend('Using PF','From data');